services:
  pep_db:
    image: postgres:13.5
    container_name: db_instalacao
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: instalacao_dev
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/data
