defmodule InstalacaoSolar.Analises.Instalacao do
  use Ash.Resource

  actions do
    defaults [:create, :read, :update, :destroy]
  end

  attributes do
    # Add an autogenerated UUID primary key called :id
    uuid_primary_key :id

    attribute :nome_inversor, :string do
      allow_nil? false
    end

    # simulando status de uma analise de instalacao
    attribute :status, :atom do
      # Constraints allow you to provide extra rules for the value.
      # The available constraints depend on the type
      # See the documentation for each type to know what constraints are available
      # Since atoms are generally only used when we know all of the values
      # it provides a `one_of` constraint, that only allows those values
      constraints one_of: [:finished, :in_progress, :not_started]

      default :not_started

      allow_nil? false
    end
  end
end
