defmodule InstalacaoSolar.Analises.Instalacao do
  use Ash.Resource

  actions do
    defaults [:create, :read, :update, :destroy]
  end

  attributes do
    # Add an autogenerated UUID primary key called :id
    uuid_primary_key :id

    attribute :nome_inversor, :string
  end
end
