defmodule InstalacaoSolar.Repo.Migrations.AddInstalacao do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:instalacoes, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :nome_inversor, :text, null: false
      add :status, :text, null: false, default: "not_started"
    end
  end

  def down do
    drop table(:instalacoes)
  end
end