defmodule InstalacaoSolar.Repo.Migrations.AddInstalacaoScore do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:instalacoes) do
      add :score, :bigint
    end
  end

  def down do
    alter table(:instalacoes) do
      remove :score
    end
  end
end